CREATE TABLE Account(
	Id INT IDENTITY(1,1) PRIMARY KEY,  
    PersonId INT NOT NULL,
	IBAN CHAR(22) NOT NULL UNIQUE,
	Amount DECIMAL(18,2) NOT NULL,
	Currency CHAR(3) NOT NULL,
	CONSTRAINT IBANFormatCheck CHECK(PATINDEX('GE[0-9][0-9]CD%', IBAN) = 1),
	CONSTRAINT CurrencyCheck CHECK(Currency IN('GEL','USD','EUR')),
	FOREIGN KEY (PersonId) REFERENCES Person(Id) ON DELETE CASCADE
);