CREATE TABLE Card(
	Id INT IDENTITY(1,1) PRIMARY KEY,  
    AccountId INT NOT NULL,
	CardNumber NVARCHAR(100) NOT NULL UNIQUE,
	ExpirationDate CHAR(5) NOT NULL,
	CVV NVARCHAR(100) NOT NULL,
	PIN NVARCHAR(100) NOT NULL,
	CONSTRAINT ExpirationDateCheck CHECK(PATINDEX('[0-9][0-9]/[0-9][0-9]', ExpirationDate) = 1),
	FOREIGN KEY (AccountId) REFERENCES Account(Id) ON DELETE CASCADE
);