CREATE TABLE RefreshToken (
    Id INT IDENTITY(1,1) PRIMARY KEY,  
    IdentityUserId NVARCHAR(450) NOT NULL, 
    Token NVARCHAR(450) NOT NULL UNIQUE,
    ExpirationDate DATETIME NOT NULL,
	DeviceId NVARCHAR(450) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (IdentityUserId) REFERENCES AspNetUsers(Id) ON DELETE CASCADE
);